### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by CodingSinger** [wookayin/vim-typora#1]

**Comment by wind13** [comment]
Same question, how to use it? I open Typora, and then what?

**Comment by wookayin** [comment]
It simply opens the markdown file in Typora windows. Bidirectional synchronization between vim buffer and Typora are taken care of by the applications.

**Comment by hollyhudson** [comment]
> Same question, how to use it? I open Typora, and then what?

You don't need to open Typora first.  While editing your vim file, go into escape mode and type `:Typora`.  Typora will launch itself with the contents of the file you are editing displayed.
