### ISSUE TITLE
I typed ":Typora" but nothing happened

### ISSUE THREAD

**Issue by Boltzmachine** [wookayin/vim-typora#3]
in my .vimrc
`source ~/typora.vim`
but as I
`:Typora`
nothing happened.

**Comment by xkstein** [comment]
What OS/editor are you using?

**Comment by Boltzmachine** [comment]
macOS 
Catalina 10.15
And NeoVim

**Comment by xkstein** [comment]
[My branch](https://github.com/xkstein/vim-typora) should work. Its only like a one line change if you'd rather just edit typora.vim

**Comment by xkstein** [comment]
@weikang-q Did that work for you?

**Comment by Boltzmachine** [comment]
Sorry for my late reply.
It works!
Thanks very much.

**Comment by xkstein** [comment]
Great, glad to hear

**Comment by my0811** [comment]
Creat,glad to hear

**Comment by wookayin** [comment]
These days, Typora has Unix and Windows support, so it should work in all platforms (#4). Sorry I didn't include any warning messages for unsupported platforms back then when I first wrote this...
